version: "3"
services:
  db:
    container_name: helloteam.db
    image: mysql:5.7
    ports:
      - '3309:3306'
    environment:
       MYSQL_DATABASE: 'helloteam_db'
       MYSQL_ROOT_PASSWORD: 'docker'
    volumes:
      - ./tmp/helloteam/mysql:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  api:
    container_name: helloteam.api
    env_file:
      - .env
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - mailhog
    links:
      - db
      - mailhog
