version: "3"
services:
  db:
    container_name: helloteam.db
    image: mysql:5.7
    ports:
      - '3309:3306'
    environment:
       MYSQL_DATABASE: 'helloteam_db'
       MYSQL_ROOT_PASSWORD: 'docker'
    volumes:
      - ./tmp/helloteam/mysql:/var/lib/mysql

  web:
    container_name: helloteam.web
    env_file:
      - .env
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db
