# Generated by Django 3.1.4 on 2021-03-25 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workspace',
                'verbose_name_plural': 'Workspaces',
                'db_table': 'workspace',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceStaff',
            fields=[
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='workspace_staff', serialize=False, to='workspace.workspace')),
                ('role', models.CharField(choices=[('C', 'Coach'), ('A', 'Assistant')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WorkspaceStaff',
                'verbose_name_plural': 'WorkspaceStaffs',
                'db_table': 'workspace_staff',
                'unique_together': {('workspace', 'user')},
            },
        ),
        migrations.CreateModel(
            name='WorkspaceAthlete',
            fields=[
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='workspace_athletes', serialize=False, to='workspace.workspace')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WorkspaceAthlete',
                'verbose_name_plural': 'WorkspaceAthletes',
                'db_table': 'workspace_athlete',
                'unique_together': {('workspace', 'user')},
            },
        ),
    ]
