# Generated by Django 3.1.4 on 2021-04-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210415_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified_email',
            field=models.BooleanField(default=False, verbose_name='verified email'),
        ),
    ]
